
version: '3.4'

services:
  webcode:
    container_name: webcode
    build:
      context: .
      args:
        BASE_TAG: linuxserver/code-server:${CODE_SERVER_ARCHITECTURE}-${CODE_SERVER_VERSION}
        CODE_SERVER_VERSION: ${CODE_SERVER_VERSION:?err}
        CODE_SERVER_ARCHITECTURE: ${CODE_SERVER_ARCHITECTURE:?err}
    image: test:${VERSION:?err}
    logging:
      driver: "json-file"
      options:
        max-size: "2g"
        max-file: "3"
    environment:
      - PUID=${UID:?err}
        # should have access to the docker socket
      - PGID=${GID:?err}
      - DEFAULT_WORKSPACE=/config/workspace
      
    volumes:
      # mount docker sockt, to be able to restart container
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CODE_WORKSPACE_PATH:?err}:/config/workspace
      - ${CODE_CONFIG_PATH:?err}:/config
    ports:
      - 8888:8443
