name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        source .build 
        docker build . --file Dockerfile --tag christianfehlinger/code:$VERSION --build-arg BASE_TAG=linuxserver/code-server:${CODE_SERVER_ARCHITECTURE}-${CODE_SERVER_VERSION}  --build-arg CODE_SERVER_VERSION=$CODE_SERVER_VERSION  --build-arg CODE_SERVER_ARCHITECTURE=$CODE_SERVER_ARCHITECTURE
